### ISSUE TITLE
The sourcespawn compiler has crashed.

### ISSUE THREAD

**Issue by Lantejoula** [SPCodeOrg/SPCode#100]
Hey, 

When i try to compile something, my SPCode send me this warn: https://prnt.sc/1uev5m6

I need how i can fix them.

Lantejoula

**Comment by azalty** [comment]
Re-install 1.8.0.1, the original release was broken.
You can just replace SPCode.exe from the Portable .zip archive

**Comment by maxijabase** [comment]
Yes, this was an unfortunate wrong release. That is a trunk version of SPCode. Reinstall it dragging only the executable from the portable, as azalty suggests. SDorry for the inconveniences!
