### ISSUE TITLE
Autocomplete window is shown on an empty line with indentation

### ISSUE THREAD

**Issue by azalty** [SPCodeOrg/SPCode#120]
**Version**
SPCode Beta rev 1094

**Describe the bug**
The autocomplete window is shown when on an empty line with a tabulation, hiding things and making us unable to create a new line with enter, since it would write the first definition found instead.

**To Reproduce**
1. Create a new line with at least 1 indentation (tab)
2. The autocomplete window appears
3. Press enter and cry.

**Screenshots**
![image](https://user-images.githubusercontent.com/36737524/157919167-14f87608-f839-433c-9510-788908ed7443.png)

**Comment by azalty** [comment]
Still not fixed as of rev 1149 though

**Comment by maxijabase** [comment]
I can't seem to reproduce this in 1149.

**Comment by azalty** [comment]
![image](https://user-images.githubusercontent.com/36737524/159820417-153ab306-03f9-4ad8-ac6f-01538f04232c.png)
Must be an include that's faulty, because we can see that the first 3 options have a tabulation at the start

This doesn't happen in the stable branch of SPCode though

**Comment by azalty** [comment]
The faulty includes:

**smlib.inc**
![image](https://user-images.githubusercontent.com/36737524/159932104-b5579152-fb7c-466f-91af-46744f8ba302.png)

**hosties.inc**
![image](https://user-images.githubusercontent.com/36737524/159932196-a1f9e7ba-7d6d-48de-aa4a-b2e0a8677902.png)

`#define + space + tab` causes this problem

**Comment by maxijabase** [comment]
Oh yeah, I just included smlib and now can reproduce. We'll see how we sort it out.

**Comment by Hexer10** [comment]
I just pushed a commit that should address this issue, it should be available in the next beta version.

**Comment by azalty** [comment]
Thanks! This seems fixed.
