### ISSUE TITLE
Find & Replace > Replace replaces the next result instead of the currently-selected result

### ISSUE THREAD

**Issue by worMatty** [SPCodeOrg/SPCode#122]
**Describe the bug**
I used the Find & Replace feature to skip through code and replace particular instances of a search term. However, when I press the Replace button, SPCode does not replace the currently-selected search result with my replacement string. Instead, it jumps to the next result and replaces that.

**To Reproduce**
1. Open Find & Replace
2. Enter a search term and some replacement text
3. Click Find
4. Press Replace

**Comment by maxijabase** [comment]
makes sense, I'll improve that mechanism
