### ISSUE TITLE
SPCode crashes on startup after latest update (1.8.2.0)

### ISSUE THREAD

**Issue by CookieCat45** [SPCodeOrg/SPCode#126]
A clear and concise description of what the bug is:
SPCode crashes a few seconds after the splash screen pops up.

1. Open SPCode.

Crash report:

2
Section: SPCODE LOADING
.NET Version: 4.0.30319.42000
Is local installation?: True
OS: Microsoft Windows NT 6.2.9200.0
64 bit OS: TRUE
64 bit mode: TRUE
Dir: C:\Users\User\Desktop\SPCode
Working Set: 86004 kb
Installed UI Culture: en-US
Current UI Culture: en-US
Current Culture: en-CA

Exception 1
Message:
The type initializer for 'SPCode.UI.Components.EditorElement' threw an exception.
Stacktrace:
   at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at SPCode.UI.Components.EditorElement..ctor(String filePath)
   at SPCode.UI.MainWindow.AddEditorElement(FileInfo fInfo, String editorTitle, Boolean SelectMe, EditorElement& editor)
   at SPCode.UI.MainWindow.TryLoadSourceFile(String filePath, EditorElement& outEditor, Boolean UseBlendoverEffect, Boolean TryOpenIncludes, Boolean SelectMe)
   at SPCode.UI.MainWindow..ctor(SplashScreen sc)
   at SPCode.Program.Main(String[] args)
Source:
PresentationFramework
HResult Code:
-2146233087
Helplink:
null
Targetsite Name:
RewrapException
Exception 2
Message:
Method not found: 'System.Collections.Generic.IEnumerable`1<SourcepawnCondenser.SourcemodDefinition.ACNode> SourcepawnCondenser.SourcemodDefinition.ACNode.ConvertFromStringList(System.Collections.Generic.IEnumerable`1<System.String>, Boolean, System.String, Boolean)'.
Stacktrace:
   at SPCode.UI.Components.EditorElement..cctor()
Source:
SPCode
HResult Code:
-2146233069
Helplink:
null
Targetsite Name:
.cctor

**Comment by maxijabase** [comment]
Do you happen to know what was the version you upgraded FROM?
Would you test if this issue occurs when downloading the portable version and executing it fresh?
Would you care to zip me your SPCode installation?

**Comment by CookieCat45** [comment]
**Do you happen to know what was the version you upgraded FROM?**
I upgraded from 1.8.1.0 to 1.8.2.0. I went to close SPCode and was prompted to update to 1.8.2.0. I chose Yes. SPCode then closed and reopened itself, crashed, and then started crashing every time I tried to open it from that point on.

**Would you test if this issue occurs when downloading the portable version and executing it fresh?**
I downloaded the portable version of 1.8.2.0 and the crash did not occur. I additionally downloaded a fresh portable version of 1.8.1.0 and updated it, and the crashing also did not occur.

**Would you care to zip me your SPCode installation?**
[SPCode.zip](https://github.com/SPCodeOrg/SPCode/files/9688241/SPCode.zip)

**Comment by maxijabase** [comment]
This definitely has something to do with a specific file(s) that was already opened in the editor before you updated to 1.8.2.0. I can see a lot of recently opened files in your installation, but they obviously won't open in my machine if they don't exist. What I could suggest to help me track down this bug is to confirm this by grabbing your broken installation's `options_0.dat` file and copying it over your fresh portable installation. This options file contains a list of the files that were opened prior to closing the program - by doing that, the portable one should attempt to open them once it boots up. If it crashes, we can be sure that's the issue.

**Comment by CookieCat45** [comment]
Copying the options_0.dat file onto the fresh installation did not trigger any crashes. However after deleting the options_0.dat file from the broken installation, SPCode starts without crashing.

**Comment by maxijabase** [comment]
I guess it's not too bad of a thing nor unsolvable after all, but it's always annoying to lose all your settings by deleting the options file just to get SPCode to start again... sorry about that, will investigate ways to reduce these situations in the future.
