### ISSUE TITLE
[Bug] Custom includes in scripting dirs on other drives are seemingly ignored when compiling

### ISSUE THREAD

**Issue by worMatty** [SPCodeOrg/SPCode#84]
Howdy.

If you specify more than one scripting dir, and at least one of them is on another drive, any custom includes the dir on the other drive contains won't be used when compiling.

Here we have our SM and custom includes in one folder on the same drive as SPCode. This works fine.
`SMDirectory=".\sourcepawn\configs\sm_1_10_0_6478;`

Here we have our SM and custom includes in one folder on a different drive to SPCode. This works fine.
`SMDirectory="D:\TF2 mapping\SourceMod Scripting\SPEdit Configs\sm_1_10_6459;`

Here we have our SM includes in a local dir, and custom includes in a dir on another drive. Custom includes aren't picked up.
`SMDirectory=".\sourcepawn\configs\sm_1_10_0_6478;D:\TF2 mapping\SourceMod Scripting\SPEdit Configs\sm_1_10_6459;`

Here we have SM includes in a dir on another drive, and custom includes in a dir on another drive. SM includes work, custom ones do not.
`SMDirectory="D:\TF2 mapping\SourceMod Scripting\SPEdit Configs\sm_1_10_0_6478;D:\TF2 mapping\SourceMod Scripting\SPEdit Configs\sm_1_10_6459;`

The order of the dirs in the config doesn't make a difference to compiling, but it *does* affect the display of includes in the right pane of SPCode. Only the files belonging to the first dir in the config are shown. I suspect this is a separate issue though.

A directory junction (symlink) on the local drive that points to the dir on the other drive doesn't fix the problem.

**Comment by maxijabase** [comment]
In commit https://github.com/SPCodeOrg/SPCode/commit/06b32b341d909a7ce15eae9987fda3ab8641ad4b
the program now displays a log whenever you select a config that has a directory SPCode could not access to. You also get a warning message everytime you add a scripting directory to your config that the program could not get access to. The problem itself cannot be solved unless you start SPCode with administrator privileges, but you would theoretically know exactly what's wrong with your includes parsing. This will be shipped with the new release, but whoever has this problem and would like to test this out, contact me in the SPCode Discord server and I'll hand you a build.
