### ISSUE TITLE
About the messy file path in the compilation result

### ISSUE THREAD

**Issue by Cola-Ace** [SPCodeOrg/SPCode#87]
When the compiled path contains Chinese, the compiled result will be garbled, I think it may be because of the encoding format, can I convert the encoding format of the compiled result after selecting Chinese language to make Chinese displayed normally? (not a particularly important issue, but this seems unbearable)
Forgive my broken English :)

**Comment by ratawar** [comment]
Hey what's up! Do you mean if the spcomp.exe compiler path contains Chinese characters, something will go wrong?

**Comment by Cola-Ace** [comment]
Compile path contains Chinese will not have any effect on the compilation result, only the Chinese will be messed up in the spcode, usually the Chinese will be replaced with the following characters: �޹˾

**Comment by maxijabase** [comment]
Hello @Cola-Ace in case you're still interested in helping me figure this out, I'd like you to show me screenshots/videos reproducing this issue so I can know exactly what's going on and how to work on it, thank you!

**Comment by maxijabase** [comment]
Closing this in the meantime.
