### ISSUE TITLE
[Request] Open a new blank file without the faff of having to save a template somewhere

### ISSUE THREAD

**Issue by worMatty** [SPCodeOrg/SPCode#89]
I'd like to be able to create a new, blank, unsaved file within the app just by clicking File > New and have it immediately appear. I find the template system just gets in the way, and I think it should be moved to a separate option. Thanks.

**Comment by Natanel-Shitrit** [comment]
Long forgotten "feature" i wanted to add, nice one.

**Comment by maxijabase** [comment]
Sure, shouldn't be complicated
