### ISSUE TITLE
[Request] Rebindable hotkeys.

### ISSUE THREAD

**Issue by sniggyfigbat** [SPCodeOrg/SPCode#95]
It would be very helpful to have hotkey configuration loaded from a config file. If nothing else, it would give new users somewhere to look to find out what hotkeys are available.

A stretch goal / alternative might be to have preset configurations which conform to hotkeys from other major IDEs.

**Comment by maxijabase** [comment]
Although there's no guarantee this will end in a feature, I've sketched some ideas as to how to approach this request. We'll see if we end up making something useful regarding keyboard shortcuts as a whole.
